enabled_locales: ["en", "vi"]
name:
  maximum: 50
email:
  maximum: 255
pass:
  minimum: 6
gravita:
  size: 80
perpage: 20
one: "1"
two: 2
perpage: 20
content:
  maximum: 140
microposts:
  user: 50
  size: 5
current_user: 50
image_file_end: "image/jpeg,image/gif,image/png"
